# This is a basic workflow to help you get started with Actions

name: To Dev Board_2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  issues:
    types:
      - labeled

  # Allows you to run this workflow manually from the Actions tab
jobs:
  move-to-project-card:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: 'https://github.com/orgs/DraconisCluster/projects/43'
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
